advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('create/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
    
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk':self.pk})
    
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, 
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
from django.urls import reverse_lazy
from . import models

class IndexView(TemplateView):
    template_name = 'basic_app/index.html'



class SchoolListView(ListView):
    # if you don't provide context_object_name = 'schools'
    # Then it by default give name as Classname_list
    context_object_name = 'schools_list'
    model = models.School
    template_name = 'basic_app/school_list.html'


class SchoolDetailView(DetailView):
    # if you don't provide context_object_name = 'school_detail'
    # Then it by default give name as classname (with first word lowercased)
    context_object_name = 'school_details'
    model = models.School
    template_name = 'basic_app/school_detail.html'
 
class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a></li>
            <li><a class="navbar-link" href="#"></a></li>
            <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>          
            <li><a href="#"></a></li>          
        </ul>
    </nav>
    <div class="container">
        {% block body_block %} 
        {% endblock %}
    </div>
</body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %} 
    <h1>Delete {{school.name}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock %} 

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %} 
<div class="container">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School details:</h2>
    <p>Name : {{school_details.name}}</p>  
    <p>Principal : {{school_details.principal}}</p>  
    <p> Location : {{school_details.location}}</p>
    <h3>Students: </h3>

    {% for student in school_details.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
</div>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_details.pk %}">Update</a></p>
</div> 
{% endblock %} 

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %} 
    <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
    </h1>
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
{% endblock %} 

advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %} 
<h1>Welcome to a list of all the schools</h1>
    <ol>
        {% for school in schools_list %}
        <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
        {% endfor %}
    </ol>
{% endblock %}

advcbv/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="#"></a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>          
            <li><a href="#"></a></li>          
        </ul>
    </nav>
    <div class="container">
        {% block body_block %} 
        {% endblock %}
    </div>
</body>
</html>

advcbv/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %} 
<div class="jumbotron">
    <h1>Home Page!</h1>
</div>
{% endblock %}